<?php

        $form_text ="<form method='POST' action='index.php?SendMail'>\n"
                                ."<input name='frmaction' type='hidden' value='SendMail'>\n"
                                ."<table class='fborder'>\n"
                                ."<tr>\n"
                                        ."<td class='forumheader3' valign='top'>".SIMPLECONTACT_01."</td>\n"
                                        ."<td class='forumheader2'>"
                                        ."<input name='user_name' type='text' value='' maxlength='25' size='25'>"
                                        ."</td>\n"
                                ."</tr>\n"
                                ."<tr>\n"
                                        ."<td class='forumheader3' valign='top'>".SIMPLECONTACT_02."</td>\n"
                                        ."<td class='forumheader2'>"
                                        ."<input name='user_email' type='text' value='' maxlength='50' size='50'>"
                                        ."</td>\n"
                                ."</tr>\n"
                                ."<tr>\n"
                                        ."<td class='forumheader3' valign='top'>".SIMPLECONTACT_15."</td>\n"
                                        ."<td class='forumheader2'>"
                                        ."<input name='user_fone' type='text' value='' maxlength='50' size='50'>"
                                        ."</td>\n"
                                ."</tr>\n"
                                ."<tr>\n"
                                        ."<td class='forumheader3' valign='top'>".SIMPLECONTACT_03."</td>\n"
                                        ."<td class='forumheader2'>"
                                        ."<input name='user_subject' type='text' value='' maxlength='50' size='50'>"
                                        ."</td>\n"
                                ."</tr>\n"
                                ."<tr>\n"
                                        ."<td class='forumheader3' valign='top'>".SIMPLECONTACT_04."</td>\n"
                                        ."<td class='forumheader2'>"
                                        ."<textarea name='user_message' wrap='soft' rows='5' cols='37'></textarea>"
                                        ."</td>\n"
                                ."</tr>\n"
                                ."<tr>\n"
                                        ."<td colspan='2' class='forumheader' style='text-align:center;'>"
                                        ."<input name='submit' type='submit' value='".SIMPLECONTACT_05."'>"
                                        ."<input name='reset' type='reset' value='".SIMPLECONTACT_06."'>"
                                        ."</td>"
                                ."</tr>\n"
                                ."</table>\n";
?>
